version: '3.8'
services:
  pxm:
    image: ghcr.io/kobeosoft/marketplace/api/pxm:latest
    ports:
      - "3000:3000" # Remplacez le port 3000 par le port sur lequel votre application écoute
    secrets:
      - ghcr-creds
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: marketplace-api
      POSTGRES_USER: api
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

secrets:
  ghcr-creds:
    external: true
