{{- range .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      {{- if $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml $.Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ $.Release.Name }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .service.port }}
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: {{ .service.port }}
            initialDelaySeconds: 30
          resources:
            {{- toYaml .resources | nindent 12 }}
      {{- with .volumeMounts }}
      volumeMounts:
        {{- toYaml . | nindent 12 }}
      {{- end }}
  {{- with .volumes }}
  volumes:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .affinity }}
  affinity:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .tolerations }}
  tolerations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- end }}
