apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-typesense
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 8108
      targetPort: 8108
      protocol: TCP
  selector:
    app: {{ include "chart.fullname" . }}-typesense
