apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-typesense
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.typesense.replicaCount }}
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-typesense
  template:
    metadata:
      labels:
        app: "{{ $.Release.Name }}-typesense"
    spec:
      containers:
        - name: {{ $.Release.Name }}-typesense
          image: typesense/typesense:0.25.2
          ports:
            - containerPort: 8108
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 5
          env:
            - name: TYPESENSE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: typesense-api-key
                  key: TYPESENSE_API_KEY
            - name: TYPESENSE_DATA_DIR
              value: /data
          resources:
            {{- toYaml .Values.typesense.resources | nindent 12 }}
          volumeMounts:
            - name: {{ $.Release.Name }}-typesense-data
              mountPath: /data
      volumes:
        - name: {{ $.Release.Name }}-typesense-data
          persistentVolumeClaim:
            claimName: {{ $.Release.Name }}-typesense-pvc

