apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $.Release.Name }}-virtualservice
spec:
  hosts:
    - "*"
  gateways:
    - "{{ $.Release.Name }}-gateway"
  http:
    {{- range .Values.services }}
    - match:
        - uri:
            prefix: "{{ .route.uriPrefix }}"
      rewrite:
        uri: "{{ .route.uriRewrite }}"
      route:
        - destination:
            host: "{{ $.Release.Name }}-{{ .name }}.{{ $.Release.Namespace }}.svc.cluster.local"
            port:
              number: {{ .route.port }}
    {{- end }}
