# Default values for marketplace-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: marketplace-api  # Définissez la valeur de fullnameOverride ici

replicaCount: 1

imagePullSecrets:
  - name: ghcr-creds

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# Configuration spécifique pour l'API PXM
api:
  pxm:
    enabled: true
    replicaCount: 4
    image:
      repository: ghcr.io/kobeosoft/marketplace/api/pxm
      pullPolicy: IfNotPresent
      tag: "latest"
    service:
      type: ClusterIP
      port: 3000

istio:
  ingress:
    enabled: true
  gateway:
    enabled: true
    name: api-gateway
  virtualService:
    enabled: true
    routes:
      - name: pxm
        prefix: /pxm
        port: 3000

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"

livenessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 30  # Délai initial avant de commencer les sondes
  periodSeconds: 10  # Fréquence à laquelle les sondes sont effectuées


readinessProbe:
  httpGet:
    path: /ready
    port: 3000
  initialDelaySeconds: 5  # Délai initial avant de commencer les sondes
  periodSeconds: 5  # Fréquence à laquelle les sondes sont effectuées

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
