# Default values for marketplace-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

imagePullSecrets:
  - name: ghcr-creds

global:
  imageTag: "latest"
  postgresql:
    dbUser: ""
    dbPassword: ""
    dbName: "default"
  keycloak :
    user: ""
    password: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

services:
  - name: "pxm-api"
    replicaCount: 1
    image:
      repository: ghcr.io/kobeosoft/marketplace/api/pxm
    service:
      port: 3000
    route:
        uriPrefix: "/api/pxm"
        uriRewrite: "/"
        port: 3000

postgresql:
  enabled: true
  image:
    tag: "latest"  # Ou une version spécifique
  postgresqlUsername: "{{ .Values.global.postgresql.dbUser }}"
  postgresqlPassword: "{{ .Values.global.postgresql.dbPassword }}"
  postgresqlDatabase: "{{ .Values.global.postgresql.dbName }}"
  persistence:
    enabled: true
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: "10Gi"

redis:
  ## Redis settings
  auth:
    enabled: true
    password: "admin"

  ## Redis master settings
  master:
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "200m"
    persistence:
      enabled: true
      path: /data
      size: "8Gi"  # Adjust based on your needs
      storageClass: ""  # Leave blank for default, or specify storage class

  ## Redis replica settings
  replica:
    replicaCount: 2  # Number of Redis replicas
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "200m"
    persistence:
      enabled: true
      path: /data
      size: "8Gi"  # Adjust based on your needs
      storageClass: ""  # Leave blank for default, or specify storage class

  ## Network policy settings
  networkPolicy:
    enabled: false

  ## Additional configuration
  configmap: |
    maxmemory-policy: "volatile-lru"

typesense:
  replicaCount: 1
  resources:
    requests:
      memory: "1Gi"
      cpu: "100m"
    limits:
      memory: "2Gi"
      cpu: "500m"

