name: Docker Build and Push

on:
  push:
    branches: [ main ]
    paths:
      - 'services/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [pmx]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/kobeosoft/marketplace/api/${{ matrix.service }}:${{ github.sha }} ./services/${{ matrix.service }}
          docker push ghcr.io/kobeosoft/marketplace/api/${{ matrix.service }}:${{ github.sha }}
