name: Build and Push Services
on:
  push:
    branches: [ master ]
    paths:
      - 'apps/**'
      - 'libs/**'
      - 'docker/**'
      - '.github/**'
      - 'helm/**'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      docker_image_tag: ${{ steps.set_vars.outputs.docker_image_tag }}
    strategy:
      matrix:
        service: [pxm]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Docker Image Tag
        id: set_vars
        run: |
            DOCKER_IMAGE_TAG="develop-$(echo ${GITHUB_SHA} | cut -c1-7)"
            echo "DOCKER_IMAGE_TAG=$DOCKER_IMAGE_TAG" >> $GITHUB_ENV
            echo "::set-output name=docker_image_tag::$DOCKER_IMAGE_TAG"

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Service
        run: make build_and_push SERVICE=${{ matrix.service }} VERSION=$DOCKER_IMAGE_TAG


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: matootie/dokube@v1.4.0
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
          clusterName: k8s-1-28-2-do-0-fra1-1704513016681

      - name: Create Docker registry secret
        run: |
          kubectl delete secret ghcr-creds --namespace=dev --ignore-not-found
          kubectl create secret docker-registry ghcr-creds \
          --docker-server=ghcr.io \
          --docker-username=${{ github.actor }} \
          --docker-password=${{ secrets.GHCR_PAT }} \
          --namespace=dev

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: '3.13.3'

      - name: Deploy with Helm
        run: |
          helm upgrade --install marketplace-api ./helm -n dev --create-namespace --set global.imageTag=${{ needs.build.outputs.docker_image_tag }}
